### ISSUE TITLE
Gradle Error for 1.8

### ISSUE THREAD

**Issue by dixitsolanki** [bigcat/Mobile-Modbus#1]
Hi, I have download your Mobile-Modbus SRC.
I try to open it in Android Studio. But It does not open . It says that "Could not Execute build using gradle distribution 1.6" "Task wrapper not found in project"

I am using Android Studio 0.3.7 build 132.932373

Can you please suggest a method to open it in Android Studio.

Thanks

**Comment by bigcat** [comment]
I'll look into it and get back to you - sorry for the delay.

Have you tried sync'ing the project w/ the Gradle settings?

**Comment by bigcat** [comment]
Try it now and let me know if my most recent commits fixed the problem.  It builds for me on the latest android studio.
